name: "json-diff-action"
description: "Check for differences between at least 2 json files and show what member is missing by each file."

branding:
  icon: database
  color: blue

inputs:
  files:
    description: List of JSON file paths to check between each other. Should be at least 2 files.
    required: false
  search_path:
    description: Path to a folder that will be inspected to search al JSON files and compere each other.
    required: false
  search_pattern:
    description: Regular expression used on search path to find desired files.
    required: false
    default: '\\.json$'

runs:
  using: "docker"
  image: "Dockerfile"
